[project]
name = "python_leetcode_tests"
version = "0.1.0"
description = "Test solutions to coding problems"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
pythonpath = "src"
